spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/db.changelog-master.yaml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5444/workflow
    password: workflow
    username: workflow